### PR TITLE
Add romanesco-clique integration docs

### PR DESCRIPTION
**Pull request by danlamanna**

### CODE REVIEW

**Comment by danlamanna** [comment]
@ronichoudhury This is a rough overview, but I was thinking once the code is merged into clique-anb/master, the following could happen:

Link [here](https://github.com/XDATA-Year-3/analytics-sandbox/blob/34003ce98162f74935e9fc697cf3c44eb4b73d84/graphs/databases/clique-romanesco.rst#running-networkx-analyses-in-clique) to the `centrality.py` file with some details.

And maybe detail [here](https://github.com/XDATA-Year-3/analytics-sandbox/blob/34003ce98162f74935e9fc697cf3c44eb4b73d84/graphs/databases/clique-romanesco.rst#running-an-analysis-from-clique) on the Clique side of things?

**Comment by waxlamp** [comment]
Thanks @danlamanna, I will try your instructions out and see what happens.

**Comment by waxlamp** [comment]
@danlamanna I added some stuff, not precisely where you suggested.  I'll leave it to you to move things around etc.  Let me know what you think.

**Comment by danlamanna** [comment]
@ronichoudhury I made some minor clarifications - the only issue I'm having is I get the following error when running the NetworkX centrality (centrality.py:32):

```
AttributeError: 'module' object has no attribute 'log_debug'
```

Those `log_debug` calls may not even be necessary anymore.

**Comment by waxlamp** [comment]
I don't think we need those log statements - feel free to delete them
(log_debug() is a new Tangelo function that isn't in a release version yet).

**Comment by danlamanna** [comment]
done-stamp

**Comment by jeffbaumes** [comment]
Congrats @danlamanna and @ronichoudhury :star:

**Pull request merged**
